---
Name: ckanregistryservices
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\CKANRegistry\Service\ResourceFieldPopulatorInterface:
    class: SilverStripe\CKANRegistry\Service\ResourceFieldPopulator
