---
Name: ckanregistryservices
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\CKANRegistry\Service\ResourcePopulatorInterface:
    class: SilverStripe\CKANRegistry\Service\ResourcePopulator
  SilverStripe\CKANRegistry\Service\ClientInterface:
    class: SilverStripe\CKANRegistry\Service\Client
